ufo_json_rpc:
  security:
    protected_methods: ['GET', 'POST']      # protection of GET and POST requests
    token_key_in_header: 'Ufo-RPC-Token'    # Name of the key in the header

    clients_tokens:
      - '%env(resolve:UFO_API_TOKEN)%'   # token example from .env.local
